apiVersion: v1
kind: ConfigMap
metadata:
  name: fluentd-conf
data:
  fluentd.conf: |-
    # TCP input to receive logs from the forwarders
    <source>
      @type forward
      bind 0.0.0.0
      port 24224
    </source>

    # Append the tag as a field
    <filter **>
      @type record_transformer
      <record>
        tag ${tag}
      </record>
    </filter>

    # JSON logs
    <filter	k8s.printer-image-snapper.printer-image-snapper-*.printer-image-snapper k8s.kube-system.traefik-*.traefik> 
      @type parser
      key_name message
      <parse>
        @type json
      </parse>
    </filter>

    # LTSV logs
    <filter k8s.metrics.kube-prometheus-stack-operator-*.kube-prometheus-stack k8s.metrics.kube-prometheus-stack-grafana-*.grafana> 
      @type parser
      key_name message
      <parse>
        @type ltsv
        label_delimiter "="
        delimiter " "
      </parse>
    </filter>

    # HTTP input for the liveness and readiness probes
    <source>
      @type http
      bind 0.0.0.0
      port 9880
    </source>

    # Throw the healthcheck to the standard output instead of forwarding it
    <match fluentd.healthcheck>
      @type stdout
    </match>

    # Send the logs to the elasticsearch
    <match **>
      @type loki
      url http://loki:3100
      insecure_tls true

      <label>
        tag
      </label>

      <buffer>
        @type file
        path /opt/bitnami/fluentd/logs/buffers/logs.buffer
        flush_thread_count 2
        flush_interval 5s
      </buffer>
    </match>

    <label @ERROR>
      <match **>
        @type stdout
      </match>
    </label>
