apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: homer
commonLabels:
  app: homer
configMapGenerator:
  - name: homer-assets
    files:
      - assets/config.yml
resources:
  - homer.yaml
