version: "3.7"
services:
  minecraft-server:
    ports:
      - "27015:27015"
      - "25565:25565"
      - "8123:8123"

    environment:
      EULA: "TRUE"
      TYPE: FABRIC

    volumes:
      - ./data:/data
    image: itzg/minecraft-server

    container_name: mc

    tty: true
    stdin_open: true
    restart: unless-stopped
