prometheus:
  server:
    persistentVolume:
      enabled: false
  prometheusSpec:
    storageSpec:
      volumeClaimTemplate:
        spec:
          storageClassName: manual
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 10Gi
          selector:
            matchLabels:
              app: prometheus-storage
