- name: Create FreeIPA Servers
  hosts: localhost
  tasks:
    - name: Create new VM with minimal options
      community.general.proxmox_kvm:
        api_user: root@pam
        api_password: secret
        api_host: https://192.168.1.80
        name: spynal
        node: sabrewulf
