- name: Remove Proxmox enterprise repos
  hosts: proxmox
  tasks:
    - name: Open firewall ports
      ansible.builtin.iptables:
        chain: INPUT
        protocol: "{{item.protocol}}"
        destination_port: "{{item.port}}"
        ctstate: NEW
        jump: ACCEPT
        comment: "{{item.comment}}"
      with_items:
        - port: 443
          protocol: tcp
          comment: SSL
        - port: 8006
          protocol: tcp
          comment: Regular port
