---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus-node-exporter
  namespace: metrics
spec:
  serviceName: pve-exporter
  replicas: 1
  selector:
    matchLabels:
      app: pve-exporter
  template:
    metadata:
      labels:
        app: pve-exporter
    spec:
      containers:
        - name: app
          image: prompve/prometheus-pve-exporter
          resources:
            limits:
              cpu: 500m
              memory: 500Mi
          volumeMounts:
            - name: upload
              mountPath: /var/www/html/storage/upload
          ports:
            - containerPort: 8080
