apiVersion: v1
kind: ConfigMap
metadata:
  name: fluentd-conf
  namespace: fluent
data:
  fluentd.conf: |-
    # TCP input to receive logs from the forwarders
    <source>
      @type forward
      bind 0.0.0.0
      port 24224
    </source>

    <filter kube.infra.ingress-nginx.ingress-nginx-controller**>
      @type parser
      key_name message
      <parse>
        @type nginx
      </parse>
    </filter>

    <filter kube.infra.logging.kibana-kibana-**>
      @type parser
      key_name message 
      <parse>
        @type json
      </parse>
    </filter>

    # HTTP input for the liveness and readiness probes
    <source>
      @type http
      bind 0.0.0.0
      port 9880
    </source>

    # Throw the healthcheck to the standard output instead of forwarding it
    <match fluentd.healthcheck>
      @type stdout
    </match>

    # Send the logs to the elasticsearch
    <match **>
      @type elasticsearch
      include_tag_key true
      host elasticsearch
      port 9200
      logstash_format true
      suppress_type_name true

      <buffer>
        @type file
        path /opt/bitnami/fluentd/logs/buffers/logs.buffer
        flush_thread_count 2
        flush_interval 5s
      </buffer>
    </match>
