apiVersion: v1
kind: PersistentVolume
metadata:
  name: grafana-storage
  namespace: metrics
  labels:
    app: grafana-storage
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  mountOptions:
    - nolock
    - rw
  nfs:
    path: /nfsroot/grafana
    server: "192.168.1.95"
