---
apiVersion: v1
kind: Service
metadata:
  name: grafana
  namespace: logging
  labels:
    app: grafana
spec:
  ports:
    - port: 3000
  selector:
    app: grafana
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  namespace: logging
  labels:
    app: grafana
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      containers:
        - name: grafana
          image: docker.io/grafana/grafana:latest
          resources:
            limits:
              cpu: 1000m
              memory: 700Mi
            requests:
              cpu: 100m
              memory: 300Mi
          ports:
            - containerPort: 5601
