---
apiVersion: v1
kind: Service
metadata:
  name: kibana
  namespace: logging
  labels:
    app: kibana
spec:
  ports:
    - port: 5601
  selector:
    app: kibana
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: filebeat-config
  namespace: logging
  labels:
    k8s-app: filebeat
data:
  kibana.yml: |-
    xpack.security.encryptionKey: "${ENCRYPTION_KEY}"
    xpack.security.session.idleTimeout: "1h"
    xpack.security.session.lifespan: "30d"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kibana
  namespace: logging
  labels:
    app: kibana
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kibana
  template:
    metadata:
      labels:
        app: kibana
    spec:
      containers:
        - name: kibana
          image: docker.elastic.co/kibana/kibana:7.10.2
          resources:
            limits:
              cpu: 1000m
              memory: 1400Mi
            requests:
              cpu: 100m
          env:
            - name: ELASTICSEARCH_URL
              value: http://elasticsearch:9200
            - name: ELASTICSEARCH_HOSTS
              value: http://elasticsearch:9200
          envFrom:
            - secretRef:
                name: kube-logging-kibana-key
          ports:
            - containerPort: 5601
