apiVersion: v1
kind: PersistentVolume
metadata:
  name: prometheus-storage
  labels:
    app: prometheus-storage
spec:
  storageClassName: manual
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    path: /nfsroot/prometheus
    server: "192.168.1.95"
