---
apiVersion: v1
kind: Namespace
metadata:
  name: elabftw
---
apiVersion: v1
kind: Service
metadata:
  name: elabftw
  namespace: elabftw
  labels:
    app: elabftw-app
spec:
  ports:
    - port: 443
      name: web
  selector:
    app: elabftw-app
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: elabftw-ingress
  namespace: elabftw
spec:
  rules:
    - host: elabftw.astrid.tech
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: elabftw
                port:
                  name: web
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: elabftw
  namespace: elabftw
  labels:
    app: elabftw-app
spec:
  serviceName: elabftw
  replicas: 1
  selector:
    matchLabels:
      app: elabftw-app
  template:
    metadata:
      labels:
        app: elabftw-app
    spec:
      containers:
        - name: app
          image: elabftw/elabimg:latest
          resources:
            limits:
              cpu: 1000m
              memory: 500Mi
          env:
            - name: TZ
              value: America/Los_Angeles
            - name: DISABLE_HTTPS
              value: "true"
          envFrom:
            - secretRef:
                name: elabftw-db
          volumeMounts:
            - name: upload
              mountPath: /elabftw/uploads
          ports:
            - containerPort: 443
  volumeClaimTemplates:
    - metadata:
        name: upload
        labels:
          app: elabftw
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 10Gi
        storageClassName: elabftw-upload
