grafana:
  ingress:
    enabled: true
    hosts:
      - grafana.astrid.tech
    path: /

  persistence:
    type: pvc
    enabled: true
    storageClassName: manual
    accessModes:
      - ReadWriteOnce
    size: 10Gi
    finalizers:
      - kubernetes.io/pvc-protection

prometheus:
  server:
    persistentVolume:
      enabled: true
  prometheusSpec:
    scrapeInterval: "10s"

    secrets:
      - prometheus-mc-basic-auth

    additionalScrapeConfigs:
      - job_name: prometheus-external-node-exporter
        metrics_path: /prometheus/node/metrics
        scheme: https
        basic_auth:
          username: prometheus
          password_file: /etc/prometheus/secrets/prometheus-mc-basic-auth/password
        static_configs:
          - targets:
              - mc.astrid.tech

      - job_name: prometheus-external-minecraft-exporter
        metrics_path: /prometheus/minecraft/metrics
        scheme: https
        basic_auth:
          username: prometheus
          password_file: /etc/prometheus/secrets/prometheus-mc-basic-auth/password
        static_configs:
          - targets:
              - mc.astrid.tech

nodeExporter:
  extraArgs:
    - --collector.diskstats.ignored-devices=^(ram|loop|fd|(h|s|v)d[a-z]|nvme\\d+n\\d+p)\\d+$
    - --collector.thermal_zone
    - --collector.rapl
