grafana:
  ingress:
    enabled: true
    hosts:
      - grafana.astrid.tech
    path: /

  persistence:
    type: pvc
    enabled: true
    storageClassName: manual
    accessModes:
      - ReadWriteOnce
    size: 10Gi
    finalizers:
      - kubernetes.io/pvc-protection

prometheus:
  server:
    persistentVolume:
      enabled: true
  prometheusSpec:
    scrapeInterval: "10s"

nodeExporter:
  extraArgs:
    - --collector.diskstats.ignored-devices=^(ram|loop|fd|(h|s|v)d[a-z]|nvme\\d+n\\d+p)\\d+$
    - --collector.thermal_zone
    - --collector.rapl
