grafana:
  ingress:
    enabled: true
    hosts:
      - grafana.astrid.tech
    path: /

  persistence:
    type: pvc
    enabled: true
    storageClassName: manual
    accessModes:
      - ReadWriteOnce
    size: 10Gi
    finalizers:
      - kubernetes.io/pvc-protection

prometheus:
  server:
    persistentVolume:
      enabled: true
  prometheusSpec:
    scrapeInterval: "10s"

  extraScrapeConfigs:
    - job_name: prometheus-minecraft-exporter
      metrics_path: /prometheus/minecraft/metrics
      basic_auth:
        username: "prometheus"
        password: "cfgqvzjbhnwcomplicatedpasswordwjnqmd"
      static_configs:
        - targets:
            - https://external-auth-proxy
      relabel_configs:
        - source_labels: [__address__]
          target_label: instance

nodeExporter:
  extraArgs:
    - --collector.diskstats.ignored-devices=^(ram|loop|fd|(h|s|v)d[a-z]|nvme\\d+n\\d+p)\\d+$
    - --collector.thermal_zone
    - --collector.rapl
