grafana:
  ingress:
    enabled: true
    hosts:
      - grafana.astrid.tech
    path: /

  persistence:
    type: pvc
    enabled: true
    storageClassName: manual
    accessModes:
      - ReadWriteOnce
    size: 10Gi
    finalizers:
      - kubernetes.io/pvc-protection
prometheus:
  server:
    persistentVolume:
      enabled: true
  prometheusSpec:
    scrapeInterval: "10s"
