- name: Ensure service hostnames point to minikube
  block:
    - name: Get minikube's IP
      ansible.builtin.command: dig minikube +short
      register: minikube_ip

    - name: Get ingress hosts
      ansible.builtin.shell: >
        kubectl get ingress -A -o json | jq '.items[].spec.rules[].host' -r 
      register: ingress_hosts

    - name: Ensure /etc/hosts points our service hostnames to minikube
      with_list: "{{ ingress_hosts.stdout_lines }}"
      ansible.builtin.lineinfile:
        path: /etc/hosts
        regex: "{{ item | regex_replace('\\.', '\\\\.') }}"
        line: "{{ minikube_ip.stdout }}\t{{ item }}"
        create: yes
        unsafe_writes: yes # or else Docker gets angery
