---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: es-pv-a
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data/elasticsearch/a"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: es-pv-b
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data/elasticsearch/b"
