---
kind: Service
apiVersion: v1
metadata:
  name: db
  namespace: firefly-iii
  labels:
    app: firefly-db
spec:
  selector:
    app: firefly-db
  clusterIP: None
  ports:
    - port: 3306
      name: mysql
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: firefly-db-pvc
  namespace: firefly-iii
  labels:
    app: firefly-db
spec:
  storageClassName: manual
  volumeName: firefly-iii-data
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: db
  namespace: firefly-iii
  labels:
    app: firefly-db
spec:
  selector:
    matchLabels:
      app: firefly-db
  template:
    metadata:
      labels:
        app: firefly-db
    spec:
      containers:
        - name: app
          image: yobasystems/alpine-mariadb:latest
          resources:
            limits:
              cpu: 1000m
              memory: 500Mi
          env:
            - name: MYSQL_RANDOM_ROOT_PASSWORD
              value: "yes"
            - name: MYSQL_USER
              value: firefly
            - name: MYSQL_DATABASE
              value: firefly
          envFrom:
            - secretRef:
                name: firefly-db-secret
          volumeMounts:
            - name: db-data
              mountPath: /var/lib/mysql
          ports:
            - containerPort: 3306
              name: mysql
      volumes:
        - name: db-data
          persistentVolumeClaim:
            claimName: firefly-db-pvc
