---
apiVersion: v1
kind: Service
metadata:
  name: firefly
  namespace: firefly-iii
  labels:
    app: firefly-app
spec:
  selector:
    app: firefly-app
  clusterIP: None
  ports:
    - port: 8080
      name: web
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: firefly-upload-pvc
  namespace: firefly-iii
  labels:
    app: firefly-app
spec:
  storageClassName: manual
  volumeName: firefly-iii-upload
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: firefly
  namespace: firefly-iii
  labels:
    app: firefly-app
spec:
  selector:
    matchLabels:
      app: firefly-app
  template:
    metadata:
      labels:
        app: firefly-app
    spec:
      containers:
        - name: app
          image: registry.hub.docker.com/jc5x/firefly-iii:latest
          env:
            - name: MYSQL_RANDOM_ROOT_PASSWORD
              value: "yes"
            - name: MYSQL_USER
              value: firefly
            - name: MYSQL_DATABASE
              value: firefly
          envFrom:
            - secretRef:
                name: firefly-app-secret
          volumeMounts:
            - name: upload
              mountPath: /var/www/html/storage/upload
      volumes:
        - name: upload
          persistentVolumeClaim:
            claimName: firefly-upload-pvc
