---
apiVersion: v1
kind: Service
metadata:
  name: firefly
  namespace: firefly-iii
  labels:
    app: firefly-app
spec:
  selector:
    app: firefly-app
  clusterIP: None
  ports:
    - port: 8080
      name: web
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: firefly-iii-upload
  labels:
    app: firefly-app
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  local:
    path: /data/firefly/upload
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - crappertop
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: firefly-upload-pvc
  namespace: firefly-iii
  labels:
    app: firefly-app
spec:
  storageClassName: manual
  volumeName: firefly-iii-upload
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: firefly
  namespace: firefly-iii
  labels:
    app: firefly-app
spec:
  selector:
    matchLabels:
      app: firefly-app
  template:
    metadata:
      labels:
        app: firefly-app
    spec:
      containers:
        - name: app
          image: registry.hub.docker.com/jc5x/firefly-iii:latest
          env:
            - name: DB_CONNECTION
              value: mysql
            - name: DB_HOST
              value: db
            - name: DB_PORT
              value: "3306"
            - name: DB_DATABASE
              value: firefly
            - name: DB_USERNAME
              value: firefly
          envFrom:
            - secretRef:
                name: firefly-app-secret
          volumeMounts:
            - name: upload
              mountPath: /var/www/html/storage/upload
          ports:
            - containerPort: 8080
      volumes:
        - name: upload
          persistentVolumeClaim:
            claimName: firefly-upload-pvc
