---
apiVersion: v1
kind: Service
metadata:
  name: firefly
  namespace: firefly-iii
  labels:
    app: firefly
spec:
  ports:
    - port: 8080
      name: web
  selector:
    app: firefly-app
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: firefly-ingress
  namespace: firefly-iii
spec:
  rules:
    - host: firefly.test.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: firefly
                port:
                  number: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: firefly
  namespace: firefly-iii
  labels:
    app: firefly-app
spec:
  selector:
    app: firefly-app
  ports:
    - port: 8080
      name: web
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: firefly
  namespace: firefly-iii
  labels:
    app: firefly-app
spec:
  serviceName: firefly
  replicas: 1
  selector:
    matchLabels:
      app: firefly-app
  template:
    metadata:
      labels:
        app: firefly-app
    spec:
      containers:
        - name: app
          image: registry.hub.docker.com/jc5x/firefly-iii:latest
          resources:
            limits:
              cpu: 1000m
              memory: 500Mi
          env:
            - name: DB_CONNECTION
              value: mysql
            - name: DB_HOST
              value: db
            - name: DB_PORT
              value: "3306"
            - name: DB_DATABASE
              value: firefly
            - name: DB_USERNAME
              value: firefly
          envFrom:
            - secretRef:
                name: firefly-app-secret
          volumeMounts:
            - name: upload
              mountPath: /var/www/html/storage/upload
          ports:
            - containerPort: 8080
  volumeClaimTemplates:
    - metadata:
        name: upload
        labels:
          app: firefly-iii
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 10Gi
