---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: firefly-iii-data
  labels:
    app: firefly-db
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  local:
    path: /data/firefly/db
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - crappertop
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: firefly-iii-upload
  labels:
    app: firefly-app
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  local:
    path: /data/firefly/upload
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - crappertop
