- name: Remove Proxmox enterprise repos
  hosts: proxmox
  tasks:
    - name: Install Pip
      apt:
        name: python-pip
        state: latest
        update_cache: yes
        cache_valid_time: 3600

    - name: Ensure pip requirements are installed
      become: true
      pip:
        name: proxmoxer
        state: present

    - name: Create new VM with minimal options and given vmid
      community.general.proxmox_kvm:
        api_user: root@pam
        api_password: secret
        api_host: helldorado
        node: "{{pve_kube_node}}"
        name: "{{pve_kube_node}}.kube.p.astrid.tech"
        cores: "{{pve_kube_cores}}"
        memory: "{{pve_kube_memory}}"
        balloon: "{{pve_kube_memory_min}}"
        pool: kubernetes
        ide:
          ide2: "local:cloudinit,format=qcow2"
        sshkeys:
        searchdomains: "p.astrid.tech"
        net:
          net0: "virtio,bridge=vmbr1,tag=77"
        ipconfig:
          ipconfig0: "ip=192.168.1.1/24"
