- name: Install FreeIPA
  become: true
  hosts: freeipa
  tasks:
    - name: Ensure FreeIPA Server is installed
      ansible.builtin.dnf:
        name:
          - freeipa-server
        state: latest
        update_cache: yes

    - name: Open required ports
      ansible.posix.firewalld:
        service: freeipa-ldaps
        permanent: yes
        immediate: yes
