- name: Install FreeIPA
  become: true
  hosts:
    - ipaserver
    - ipareplicas
  tasks:
    - name: Ensure packages are installed
      ansible.builtin.dnf:
        name: "{{item}}"
        state: latest
      with_items:
        - freeipa-server
        - freeipa-server-dns
        - firewalld

    - name: Ensure firewalld is enabled
      ansible.builtin.systemd:
        state: started
        name: firewalld
        enabled: yes

    - name: Open required ports
      ansible.posix.firewalld:
        service: "{{item}}"
        permanent: yes
        immediate: yes
        state: enabled
      with_items:
        - freeipa-ldaps
        - ldap
        - ldaps
        - ntp
        - http
        - https
        - dns
        - ssh
