all:
  hosts:
    dns:
      ansible_host: 192.168.1.192
      ansible_user: root
    ipa0:
      ansible_host: 192.168.1.193
      ansible_user: ayu
    ipa1:
      ansible_host: 192.168.1.194
      ansible_user: root

pi_hole:
  hosts:
    dns:

ipaserver:
  hosts:
    ipa0:
  vars:
    ipaserver_install_packages: no
    ipaserver_domain: astrid.tech
    ipaserver_realm: ASTRID.TECH
    ipaserver_setup_dns: yes
    ipaserver_auto_forwarders: yes

ipareplicas:
  hosts:
    ipa1:

pkg_apt:
  hosts:
    dns:

pkg_dnf:
  hosts:
    ipa0:
    ipa1:
