all:
  hosts:
    ipa0:
      ansible_host: 192.168.1.192
      ansible_user: ayu
    ipa1:
      ansible_host: 192.168.1.193
      ansible_user: root
    leibniz:
      ansible_host: 192.168.1.121
      ansible_user: root
influxdb:
  hosts:
    leibniz:
ipaserver:
  hosts:
    ipa0:
  vars:
    ipaserver_install_packages: no
    ipaserver_domain: astrid.tech
    ipaserver_realm: ASTRID.TECH
    ipaserver_setup_dns: yes
    ipaserver_auto_forwarders: yes
ipareplicas:
  hosts:
    ipa1:

distro_fedora:
  hosts:
    ipa0:
    ipa1:
