- name: Set up and initialize Kubernetes
  hosts: all
  become: true
  tasks:
    - name: Check if there's a Kubernetes master running
      when: node_is_master
      stat:
        path: /etc/kubernetes/admin.conf
      register: master_already_running

    - name: Initialize the Kubernetes cluster using kubeadm
      when: node_is_master and not master_already_running.stat.exists
      shell: kubeadm init --apiserver-advertise-address="{{ node_ip }}" --node-name {{ node_name }} --pod-network-cidr=10.8.0.0/16
      register: master_init_result

    - name: Fetch kubernetes config
      when: node_is_master
      fetch:
        src: /etc/kubernetes/admin.conf
        dest: ~/.kube/config
        flat: yes
        backup: yes

    - name: Install Tigera Calico operator
      when: node_is_master
      command: kubectl apply -f https://docs.projectcalico.org/manifests/tigera-operator.yaml
      environment:
        KUBECONFIG: /etc/kubernetes/admin.conf

    - name: Copy customized Calico resource file
      when: node_is_master
      copy:
        src: ./calico/custom-resources.yaml
        dest: /root/calico-custom-resources.yaml
        force: yes

    - name: Apply customized Calico resources
      when: node_is_master
      command: kubectl apply -f /root/calico-custom-resources.yaml
      environment:
        KUBECONFIG: /etc/kubernetes/admin.conf

    - name: Generate join command
      when: node_is_master
      raw: kubeadm token create --print-join-command > /tmp/kube-join-command

    - name: Copy join command master -> controller
      when: node_is_master
      fetch:
        src: /tmp/kube-join-command
        dest: /tmp/kube-join-command
        flat: yes
        force: yes

    - name: Copy join command controller -> nodes
      when: not node_is_master
      copy:
        src: /tmp/kube-join-command
        dest: /tmp/kube-join-command
        force: yes

    - name: Join nodes to cluster
      when: not node_is_master
      raw: cat /tmp/kube-join-command | sh
