- name: Upgrade packages
  hosts: all
  strategy: free
  become: true
  tasks:
    - name: Upgrade Apt packages
      when: "'pkg_apt' in group_names"
      apt:
        name: "*"
        state: latest
        update_cache: yes
    - name: Upgrade DNF packages
      when: "'pkg_dnf' in group_names"
      dnf:
        name: "*"
        state: latest
        update_cache: yes
