- name: Prevent lid switch from suspending machine
  ansible.builtin.lineinfile:
    line: "{{ item }}"
    state: present
    path: /etc/systemd/logind.conf
  with_items:
    - HandleLidSwitch=ignore
    - HandleLidSwitchExternalPower=ignore
    - HandleLidSwitchDocked=ignore
    - HandlePowerKey=poweroff

- name: Reload systemd-logind
  systemd:
    name: systemd-logind.service
    state: restarted
