repositories:
  - name: kubernetes-dashboard
    url: https://kubernetes.github.io/dashboard/
  - name: bitnami
    url: https://charts.bitnami.com/bitnami
  - name: fluent
    url: https://fluent.github.io/helm-charts
  - name: prometheus-community
    url: https://prometheus-community.github.io/helm-charts
  - name: grafana
    url: https://grafana.github.io/helm-charts
releases:
  - name: loki
    namespace: logging
    chart: grafana/loki
    values:
      - ./monitoring/loki.yaml

  - name: fluent-bit
    namespace: logging
    chart: fluent/fluent-bit
    values:
      - ./monitoring/fluent-bit.yaml

  - name: fluentd
    namespace: logging
    chart: bitnami/fluentd
    values:
      - ./monitoring/fluentd-agg.yaml

  - name: kube-prometheus-stack
    namespace: metrics
    chart: prometheus-community/kube-prometheus-stack
    values:
      - ./monitoring/prometheus-stack.yaml

  - name: kubernetes-dashboard
    namespace: kubernetes-dashboard
    chart: kubernetes-dashboard/kubernetes-dashboard
    values:
      - ./monitoring/kubernetes-dashboard.yaml

  - name: kube-state-metrics
    namespace: kube-state-metrics
    chart: bitnami/kube-state-metrics
