- hosts: maas
  vars:
    maas_adminusers:
      - username: "root"
        email: "admin@{{ maas_dns_domain }}"
        password: lookup('password', 'credentials/maas/root.txt chars=ascii_letters,digits')
    maas_dns_domain: "server.maas"
    maas_region_controller: "192.168.250.10"
    maas_region_controller_url: "http://{{ maas_region_controller }}:5240/MAAS"
    maas_repo: "ppa:maas/stable"

    # Defines if maas user should generate ssh keys
    # Usable for remote KVM/libvirt power actions
    maas_setup_user: false

    maas_single_node_install: true
  roles:
    - role: ansible-maas
  tasks:
