---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus-node-exporter
  namespace: metrics
  labels:
    app: firefly
spec:
  serviceName: firefly
  replicas: 1
  selector:
    matchLabels:
      app: firefly-app
  template:
    metadata:
      labels:
        app: firefly-app
    spec:
      containers:
        - name: app
          image: prompve/prometheus-pve-exporter
          resources:
            limits:
              cpu: 500m
              memory: 500Mi
          env:
            - name: DB_CONNECTION
              value: mysql
            - name: DB_HOST
              value: db
            - name: DB_PORT
              value: "3306"
            - name: DB_DATABASE
              value: firefly
            - name: DB_USERNAME
              value: firefly
          envFrom:
            - secretRef:
                name: firefly-app-secret
          volumeMounts:
            - name: upload
              mountPath: /var/www/html/storage/upload
          ports:
            - containerPort: 8080
  volumeClaimTemplates:
    - metadata:
        name: upload
        labels:
          app: firefly-iii
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 10Gi
